services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        daphne ${PROJECT_NAME}.asgi:application -b 0.0.0.0 -p 8000
      "
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - redis
    container_name: ${CONTAINER_PREFIX}-app
    environment:
      - VIRTUAL_HOST=${TEST_DOMAIN_NAME}
      - LETSENCRYPT_HOST=${TEST_DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${USER_EMAIL}
      - PROJECT_NAME=${PROJECT_NAME}
      - CONTAINER_PREFIX=${CONTAINER_PREFIX}

  redis:
    image: redis:latest
    container_name: ${CONTAINER_PREFIX}-redis
    environment:
      - CONTAINER_PREFIX=${CONTAINER_PREFIX}
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DEFAULT_HOST=${TEST_DOMAIN_NAME}

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/acme.sh:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx_reverse_proxy
      - DEFAULT_EMAIL=${USER_EMAIL}

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for web and redis...';
        while ! nc -z web 8000 || ! nc -z redis 6379; do
          sleep 1;
        done;
        echo 'Web and Redis are up - starting celery worker';
        celery -A ${PROJECT_NAME} worker --loglevel=info
      "
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    container_name: ${CONTAINER_PREFIX}-celery
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - CONTAINER_PREFIX=${CONTAINER_PREFIX}
