# Generated by Django 5.2.7 on 2025-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_condition_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='callback_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='callback_url',
            field=models.URLField(blank=True, max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='total_images',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
