# Generated by Django 5.2.7 on 2025-10-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_condition_analysis', '0002_analysistask_callback_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Property ID'),
        ),
    ]
