# Generated by Django 5.2.7 on 2025-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_condition_analysis', '0003_analysistask_property_id_property_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('super_id', models.CharField(db_index=True, max_length=1028, verbose_name='Super ID')),
                ('property_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Property ID')),
                ('context', models.CharField(default='image_condition_analysis', max_length=64, verbose_name='Context')),
                ('status', models.CharField(default='STARTED', max_length=64, verbose_name='Status')),
                ('stage', models.CharField(blank=True, max_length=128, null=True, verbose_name='Stage')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='Progress')),
                ('data_location', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Data Location')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last Error')),
            ],
            options={
                'verbose_name': 'Workflow Status',
                'verbose_name_plural': 'Workflow Statuses',
                'db_table': 'workflow_status',
                'indexes': [models.Index(fields=['property_id'], name='idx_workflow_status_prop_id'), models.Index(fields=['super_id'], name='idx_workflow_status_super_id')],
                'constraints': [models.UniqueConstraint(fields=('super_id', 'context'), name='uq_workflow_status_context')],
            },
        ),
    ]
